### PR TITLE
Fix json tag

### LINKED ISSUE #5: `CreatePage` function always return 400 error
First of all ,thanks for creating the notino-sdk for go. 

when the following code execute always return 400 error. 

`go version go1.15.6 darwin/amd64`

```
func getClient(apiKey string) *notion.Client {
	return notion.NewClient(apiKey)
}

func createPage(c echo.Context) error {
	notionApi := os.Getenv("NOTION_API")
	client    := getClient(notionApi)
	ctx       := context.Background()
	parentId  := "{page_id}"

	titleText := &notion.Text{
		Content: "this is a title of the created page",
	}
	title := []notion.RichText{
		{
			Type: notion.RichTextTypeText,
			Text: titleText,
		},
	}
	params := notion.CreatePageParams{
		ParentType: notion.ParentTypePage,
		ParentID:   parentId,
		Title:      title,
	}

	page, err := client.CreatePage(ctx, params)
	if err != nil {
		fmt.Printf("%s",err)
	}
        fmt.Println(page)
	return nil
}
```

The following error code will be returned when `createPage` function is executed.

```
notion: failed to create page: body failed validation. Fix one: body.parent.type should be not present, instead was `"database_id"`. body.parent.page_id should be defined, instead was `undefined`. (code: validation_error, status: 400)
```

I think the structure is correct, so I'm thinking there's probably something wrong with the code.

Thank you .

### PR DESCRIPTION
**Pull request by sivchari**
close #5 
I fix [the PR](https://github.com/dstotijn/go-notion/commit/d2010129197f1cfd484baacab79f02da91a4f9cf).

I've done following .
- [x] change ParentTypePageto ParentTypeDatabase.
- [x] modify expPostBody to correct expPostBody and expResponse to correct expResponse.
- [x] check the Postbody if it isn't included `type` of DatabasePageProperty.

BTW,  I think that it's better to set up CI test.  
If CI is set up, it's so easy to confirm what it is failed and how to do.  

e.g. following
```
name: test_and_lint

on:
  push:
    paths-ignore:
      - '*.md'
  pull_request:
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
       go-version: ['1.16', '1.15', '1.14']
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.goarch }}

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Restore cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go

      - name: Get dependencies
        run: |
          go mod download

      - name: Test
        run: go test -v ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.29
          args: --disable-all --enable=goimports --enable=golint --enable=govet --enable=errcheck
```

I've wrote out the code above, so if there's anything you want me to fix, let me know.
I'm thinking of fixing it and submitting it as a PR.
How about you this proposal？

### CODE REVIEW

File: client_test.go [hunk 1]
```diff
@@ -907,6 +907,133 @@ func TestCreatePage(t *testing.T) {
 			},
 			expError: nil,
 		},
+		{
+			name: "valid case: ParentType is ParentTypeDatabase and successful response",
```
Comment (dstotijn) [inline client_test.go:911]: Could you please change the name to:
```suggestion
			name: "database parent, successful response",
```

And change the name for the other (existing) test case to "page parent, successful response"? 🙏

**Review by dstotijn — CHANGES_REQUESTED** [review]
Looks good, thanks! 🎉 
Left a comment on the names of the tests.
Could you also remove the `.idea` files from the PR?

**Comment by sivchari** [comment]
@dstotijn  thx for review ! I fix it :)
